#include "MapFeatureTypes.h"

LISTVALUECONST(TilePropertiesFlag, TILEPROPERTIESFLAGS_STRINGS, TILEPROPERTIESFLAGS_VALUES, TILE_PROPERTIES_SIZE);
LISTCONST(MapFeatureType, MAPFEATURES_STR, MAPFEATURES_SIZE);
