#pragma once
#define GOC_COMPLETED

#define FORCECPPPRE2011

#if !defined(FORCECPPPRE2011)
#if __cplusplus >= 201103L
#define CPP2011
#endif
#endif
#include <Urho3D/Urho3D.h>

#include "DefsGame.h"

#undef SETUP_QUALITY

#if defined(RPI)
#define SETUP_QUALITY 0
#else
#define SETUP_QUALITY 1
#endif

#if defined(URHO3D_VULKAN)
#undef SETUP_QUALITY
#define SETUP_QUALITY 1
#endif

/// Always now : RenderShape with terrainatlas removed
#define USE_TILERENDERING

#if (SETUP_QUALITY == 0)
//#define ACTIVE_LAYERMATERIALS
/// ChunkBatch has less batches but can't filter MapObjectType (for drawdebug only) and Decals are under RenderColliders
//#define USE_CHUNKBATCH
#define ACTIVE_WEATHEREFFECTS
#define USE_PARTICULES
#else
#define ACTIVE_LAYERMATERIALS
#define ACTIVE_WEATHEREFFECTS
#define USE_PARTICULES
#define USE_ANIMATEDFURNITURES

#if !defined(URHO3D_VULKAN)
#define ACTIVE_RENDERTARGET
#endif
#endif

#define ACTIVE_NETWORK
#define ACTIVE_NETWORK_GRAPHICMESSAGES
#define ACTIVE_NETWORK_SIMULATOR
#define ACTIVE_NETWORK_LOGSTATS
//#define ACTIVE_NETWORK_SERVERRECONCILIATION
//#define ACTIVE_NETWORK_LOCALPHYSICSIMULATION_BUTTON_MAINONLY
//#define ACTIVE_NETWORK_LOCALPHYSICSIMULATION_VELOCITY_NONMAIN

#define ACTIVE_PRELOADER
#define ACTIVE_POOL
#define ACTIVE_CONSOLECOMMAND
#define ACTIVE_SDLMAPPINGJOYSTICK_DB
#define ACTIVE_PATHFINDER
#define ACTIVE_SPLASHUI

#define ACTIVE_CREATEMODE

#ifdef ACTIVE_CREATEMODE
    #ifdef URHO3D_ANGELSCRIPT
        #define EDITORMODE1
    #else
        #ifndef URHO3D_STATIC_DEFINE
        #define EDITORMODE2
    #else
        #define EDITORMODE3
        #endif
    #endif
#endif

//#define ACTIVE_BARYCENTRICEFFECTS_TEST
//#define ACTIVE_BARYCENTRICEFFECTS_TEST_IDENTIFY_ADJACENTEDGES
//#define ACTIVE_CLOUDEFFECTS_SCROLLINGSHAPE
//#define ACTIVE_SCROLLINGSHAPE_FRUSTUMCAMERA

//#if defined(_DEBUG)
//    #define ACTIVE_CLIPPING
//#endif

#if defined(RPI)
    #define ACTIVE_CLIPPING
    #define ACTIVE_SCROLLINGSHAPE_CLIPPING
    #define ACTIVE_RENDERSHAPE_CLIPPING
#endif

#if defined(RPI4) || defined(ANDROID)
    #define ACTIVE_CLIPPING
    #define ACTIVE_SCROLLINGSHAPE_CLIPPING
    #define ACTIVE_RENDERSHAPE_CLIPPING
#endif

#if defined(ANDROID)
    #define ACTIVE_CLIPPING
    #define ACTIVE_SCROLLINGSHAPE_CLIPPING
#endif

#define ACTIVE_RENDERSHAPE_EMBOSE
#define ACTIVE_REDUCE_TEXTURE_UV

#define ACTIVE_TIPMODE
#define ACTIVE_ALLAVATARS

//#define ACTIVE_INITIALDEZOOMONSTART

#define ACTIVE_WORLD2D_DYNAMICZOOM
#define ACTIVE_WORLD2D_PROFILING
//#define ACTIVE_WORLD2D_DEBUG
#define ACTIVE_WORLD2D_THREADING

#define ACTIVE_GAMELOGLEVEL

#define GAMELOGLEVEL_MINIMAL LOG_ERROR

//#define FORCE_DEBUGGAMELOGLEVEL

#if defined(_DEBUG) || defined(FORCE_DEBUGGAMELOGLEVEL)
//#define GAMELOGFILTER GAMELOG_PRELOAD|GAMELOG_MAPUNLOAD|GAMELOG_WORLDUPDATE|GAMELOG_WORLDVISIBLE|GAMELOG_PLAYER
//#define GAMELOGFILTER GAMELOG_PRELOAD|GAMELOG_MAPUNLOAD|GAMELOG_WORLDUPDATE|GAMELOG_WORLDVISIBLE
//#define GAMELOGFILTER GAMELOG_PRELOAD|GAMELOG_MAPPRELOAD|GAMELOG_MAPUNLOAD|GAMELOG_WORLDUPDATE|GAMELOG_WORLDVISIBLE|GAMELOG_PLAYER
//#define GAMELOGFILTER GAMELOG_PRELOAD|GAMELOG_MAPUNLOAD|GAMELOG_WORLDUPDATE|GAMELOG_WORLDVISIBLE|GAMELOG_PLAYER
//#define GAMELOGFILTER GAMELOG_PRELOAD|GAMELOG_MAPUNLOAD|GAMELOG_WORLDUPDATE|GAMELOG_WORLDVISIBLE|GAMELOG_PLAYER
//#define GAMELOGFILTER GAMELOG_PRELOAD|GAMELOG_MAPUNLOAD|GAMELOG_WORLDVISIBLE|GAMELOG_PLAYER
//    #define GAMELOGFILTER GAMELOG_PRELOAD|GAMELOG_MAPPRELOAD|GAMELOG_MAPUNLOAD|GAMELOG_WORLDVISIBLE
//#define GAMELOGFILTER GAMELOG_PRELOAD|GAMELOG_MAPUNLOAD|GAMELOG_WORLDVISIBLE|GAMELOG_PLAYER
//#define GAMELOGFILTER GAMELOG_PRELOAD|GAMELOG_MAPUNLOAD|GAMELOG_WORLDVISIBLE
//#define GAMELOGFILTER GAMELOG_PRELOAD|GAMELOG_MAPPRELOAD|GAMELOG_MAPUNLOAD|GAMELOG_WORLDVISIBLE|GAMELOG_PLAYER
#define GAMELOGFILTER GAMELOG_PRELOAD|GAMELOG_MAPPRELOAD|GAMELOG_MAPCREATE|GAMELOG_MAPUNLOAD|GAMELOG_WORLDUPDATE|GAMELOG_WORLDVISIBLE|GAMELOG_PLAYER
#else
#define GAMELOGFILTER GAMELOG_PRELOAD|GAMELOG_MAPPRELOAD|GAMELOG_MAPCREATE|GAMELOG_MAPUNLOAD|GAMELOG_WORLDUPDATE|GAMELOG_WORLDVISIBLE|GAMELOG_PLAYER
//    #define GAMELOGFILTER GAMELOG_PRELOAD|GAMELOG_MAPPRELOAD|GAMELOG_MAPCREATE|GAMELOG_MAPUNLOAD|GAMELOG_WORLDUPDATE|GAMELOG_WORLDVISIBLE
#endif

#define USE_WREN

#define USE_TOPOGRAPHY_BACKCURVEFLOOR

//#define DUMP_ANIMATORTEMPLATES
//#define DUMP_INVENTORYTEMPLATES
//#define DUMP_SOUNDTEMPLATES
//#define DUMP_EFFECTTEMPLATES
//#define DUMP_ATTRIBUTES
//#define DUMP_SCENE_BEFORERESET
//#define DUMP_SCENE_AFTERRESET
//#define DUMP_UI
//#define DUMP_RESOURCES
//#define DUMP_ATLASES

