#include "GameOptions.h"

#define OBJECTPOOL_LOCALIDSONLY

//#define LOCAL_STORAGE
#define XMLMODE
#define HANDLE_ENTITIES
#define HANDLE_FURNITURES
//#define HANDLE_SAVEDISCOVEREDMAPS
#define HANDLE_TILEMODIFIERS
#define HANDLE_CONNECTED_TILES
#define HANDLE_CONNECTED_BORDERS
#define HANDLE_BACKGROUND_LAYERTILED
//#define HANDLE_BACKGROUND_IMAGE
#define HANDLE_BACKGROUND_LAYERS
#define HANDLE_BACKSCROLLERS
#define HANDLE_MINIMAP
//#define HANDLE_SCORES

//#define DRAWDEBUG_MAPBORDER
//#define DRAWDEBUG_CHUNKBORDER
//#define DRAWDEBUG_FEATURES
//#define DRAWDEBUG_MAPTOPOGRAPHY
//#define DRAWDEBUG_EFFECTZONE
//#define DRAWDEBUG_SCROLLERS
//#define DRAWDEBUG_BIOMEMAP
#define DRAWDEBUG_MAPSTATUS
#define DRAWDEBUG_MAPSPOTS
//#define DRAWDEBUG_MAPPOOL

//#define REPARENT_ENTITIES_ONMAP
//#define BUFFERED_AREA_UPDATE
//#define MAP_SAVECOLLIDERS
//#define MAP_DEFAULT_WORLDTILES
#define MAP_POPULATE_FLUID_INNERONLY
//#define DUMP_MAPDEBUG_BACKGROUND
//#define DUMP_MAPDEBUG_APPLYFEATUREVIEW
//#define DUMP_MAPDEBUG_APPLYFEATUREVIEW_MODIFIER
//#define DUMP_MAPDEBUG_FLUIDVIEW
//#define DUMP_MAPDEBUG_MASKVIEW
#define DUMP_MAPDEBUG_SETTILE
//#define DUMP_SKINWARNINGS
#define DUMP_MAPTERRAIN_LOGS
//#define DUMP_OBJECTTILED_UPDATEINFOS
//#define DUMP_ERROR_ON_TIMEOVER
//#define DUMP_MAPCREATOR_LOGS
//#define DUMP_CREATED_MAP
//#define DUMP_DRAWABLESCROLLER_WARNINGS

#define CAMERAMOVE_LERP
//#define CAMERA_TESTMODE
//#define CAMERA_TESTMODE_ULTRA
#define CAMERAFOCUS_ADJUSTWALK
//#define SCENE_REPLICATION_ENABLE

#define RESERVE_VIEWBATCHES
#define RENDER_VIEWBATCHES

#ifdef USE_TILERENDERING
#define RENDER_OBJECTTILED
#define RENDER_TERRAINS_BORDERS
#define RENDER_TERRAINS_SEWINGS
#endif

#define ACTIVE_WORLDELLIPSES
#define DRAWDEBUG_WORLDELLIPSES

#define ACTIVE_DUNGEONPLATEFORMS
#define ACTIVE_DUNGEONWINDOWS
#define ACTIVE_DUNGEONROOFS
//#if defined(_DEBUG)
//#define ACTIVE_DUNGEONRANDOMWALK
//#endif
#define RENDER_PLATEFORMS
#define RENDER_ROOFS
#define GENERATE_PLATEFORMCOLLIDERS

/// Fluid Simulator : MapSimulatorLiquid
#define FLUID_SIMULATION 5
#define FLUID_ITERATIONS 1
#define FLUID_SIMULATION_REMOVEFLOWATEMPTYBORDER
//#define FLUID_SIMULATION_UPDATEINTERVAL  0.1 // Interval for fluid simulation update in seconds
#define FLUID_SIMULATION_UPDATEINTERVAL  0.075 // Interval for fluid simulation update in seconds

/// Fluid Render : ObjectTile
#define FLUID_RENDER_USEMESH 4

//#define VALIDATE_BASSIN

#if defined(_DEBUG)
#define FLUID_RENDER_COLORDEBUG
//#define FLUID_RENDER_WATERLINE_RECTS
//#define FLUID_RENDER_DRAWDEBUG_SIMULATION
//#define FLUID_RENDER_DRAWDEBUG_SIMULATION5_MORE
//#define FLUID_RENDER_DRAWDEBUG_SIMULATION6_MORE
#define FLUID_RENDER_DRAWDEBUG_MESH
//#define FLUID_RENDER_DRAWDEBUG_SOURCE
#else
#define FLUID_RENDER_DRAWDEBUG_MESH
#endif

#define MINIMAP_NUMLAYERS 4

#define PLAYER_ACTIVEINITIALSTUFF
