#ifndef ANLV1_H
#define ANLV1_H

#include "cellulargen.h"

#include "implicitautocorrect.h"
#include "implicitbasisfunction.h"
#include "implicitbias.h"
#include "implicitblend.h"
#include "implicitbrightcontrast.h"
#include "implicitcache.h"
#include "implicitcellular.h"
#include "implicitclamp.h"
#include "implicitcombiner.h"
#include "implicitconstant.h"
#include "implicitcos.h"
#include "implicitcurve.h"
#include "implicitextractrgbachannel.h"
#include "implicitfloor.h"
#include "implicitfractal.h"
#include "implicitfunctiongradient.h"
#include "implicitgain.h"
#include "implicitgradient.h"
#include "implicitmagnitude.h"
#include "implicitnormalizecoords.h"
#include "implicitpow.h"
#include "implicitradial.h"
#include "implicitrgbadotproduct.h"
#include "implicitrotatedomain.h"
#include "implicitsawtooth.h"
#include "implicitscaledomain.h"
#include "implicitscaleoffset.h"
#include "implicitselect.h"
#include "implicitsin.h"
#include "implicitsphere.h"
#include "implicittiers.h"
#include "implicittranslatedomain.h"
#include "implicittriangle.h"

#include "rgbablend.h"
#include "rgbablendops.h"
#include "rgbacolorops.h"
#include "rgbaconstant.h"
#include "rgbacomposechannels.h"
#include "rgbacurve.h"
#include "rgbahsvtorgba.h"
#include "rgbaimplicitgrayscale.h"
#include "rgbanormalize.h"
#include "rgbargbatohsv.h"
#include "rgbarotatecolor.h"
#include "rgbaselect.h"

#include "vectortypes.h"

#endif

